-d /home/thanhduong/working/git/kiwi-nano-4k/camera_hdmi/impl/gwsynthesis/camera_hdmi.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst /home/thanhduong/working/git/kiwi-nano-4k/camera_hdmi/src/dk_video.cst
-cfg /home/thanhduong/working/git/kiwi-nano-4k/camera_hdmi/impl/pnr/device.cfg
-sdc /home/thanhduong/working/git/kiwi-nano-4k/camera_hdmi/src/dk_video.sdc
-bit
-tr
-ph
-timing
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
